sylius_grid:
    grids:
        app_file:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\File
            filters:
                exclude:
                    type: string
                    label: false
                    options:
                        fields:
                            - id
                    form_options:
                        type: not_in
                    enabled: true
                    position: 1
                search:
                    type: string
                    label: false
                    options:
                        fields:
                            - name
                    form_options:
                        type: contains
                    enabled: true
                    position: 100
                # type:
                #     type: string
                #     label: false
                #     options:
                #         fields:
                #             - type
                #     form_options:
                #         type: equal
                #     enabled: true
                #     position: 100
                type:
                    type: file_type
                    # form_options:
                    #     range: [0, 100]

            sorting:
                id: desc

            fields:
                id:
                    enabled: true
                    type: integer
                    sortable: ~
                name:
                    type: string
                    enabled: true
                    sortable: ~
                type:
                    type: string
                    enabled: true

            limits: [30, 12, 48]
