twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'clip/form/custom_types.html.twig'
        - 'bootstrap_4_layout.html.twig'
