app_clip:
    resource: |
        alias: app.clip
    type: sylius.resource

app_schedule:
    resource: |
        alias: app.schedule
    type: sylius.resource_api

app_file:
    resource: |
        alias: app.file
    type: sylius.resource_api

app_file_index:
    path: /files/
    methods: [GET]
    defaults:
        _controller: app.controller.file:indexAction
        _sylius:
            sortable: true

hls_stream:
  path: /hls/live.m3u8
  host: "localhost:8583"
