app_clip:
    resource: |
        alias: app.clip
    type: sylius.resource

app_schedule:
    resource: |
        alias: app.schedule
        grid: app_schedule
    type: sylius.resource_api

app_file:
    resource: |
        alias: app.file
        grid: app_file
    type: sylius.resource
    defaults:
        # _sylius: # Uncommenting this will remove grid filtering & sorting
        #     filterable: true
        #     sortable: true

hls_stream:
  path: /hls/live.m3u8
